name: CI CD deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: ${{ github.workspace }}
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webappcontainer:latest .

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push himanssshu/webappcontainer:latest

  test:
    runs-on: ubuntu-latest
    needs: deploy  

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/webappcontainer:latest

    - name: Run Docker container
      run: |
        docker run -d --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/webappcontainer:latest
          
    - name: Verify Docker container is running
      run: |
        docker ps  # List running containers to verify the container is up

    - name: Stop Docker container
      run: |
        docker stop test-container
          
    - name: Remove Docker container
      run: |
        docker rm test-container